import { UI_COMPONENTS_PREFIX_PATH } from "constants/route.constant";
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from "constants/navigation.constant";
import { ADMIN, USER } from "constants/roles.constant";
import { APP_PREFIX_PATH } from "constants/route.constant";

const uiComponentNavigationConfig = [
  {
    key: "uiCompodnent",
    path: "",
    title: "HR",
    translateKey: "nav.u`iComponents",
    icon: "hr",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: "appsSales.pedersoductNew",
        // path: `${APP_PREFIX_PATH}/sales/product-new`,
        title: "Work Orders",
        // translateKey: "nav.appsSales.productNew",
        icon: "crm",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },

      {
        key: "appsCrydedpto.portfolio",
        path: `${APP_PREFIX_PATH}/crypto/portfolio`,
        title: "Departments",
        // translateKey: "nav.appsCrypto.portfolio",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "Employdedees",
        path: `${APP_PREFIX_PATH}/crypto/market`,
        title: "Personnel",
        // translateKey: "nav.appsCrypto.market",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrdeypto.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Sites",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrypto.dewdwallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Perfomance",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrdewdypto.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Promotion",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrypto.waldewdlets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Terminations",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "apdedpsCrypto.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Resignations",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "apdewd2psCrypto.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Goals",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "apdwed23psCrypto.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Onboarding",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrypto.wallet4r5fr43s",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Leave",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCryptod34e43d3.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Leave Type",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsC43re4f43rdrypto.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Attendance",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCryptod34d43rf.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Shift schedules",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrferfypto.wallfrefets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Overtime",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrfrefreyfpto.walfreflets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Attendance",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrypftorfre.wafrellets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Holidays",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCfrefrypfto.walfreflets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Promotions",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCfreffrypto.walfrefrlets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Perfomamce",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "appsCrfrefyptfrefreo.wallets",
        path: `${APP_PREFIX_PATH}/crypto/wallets`,
        title: "Promotions",
        // translateKey: "nav.appsCrypto.wallets",
        icon: "issue",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
    ],
  },
];

export default uiComponentNavigationConfig;
