import { PAGES_PREFIX_PATH } from "constants/route.constant";
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
} from "constants/navigation.constant";
import { ADMIN, USER } from "constants/roles.constant";

const pagesNavigationConfig = [
  {
    key: "pageds",
    path: "",
    title: "Me",
    translateKey: "nav.pages.pages",
    icon: "me",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: "pages.welcome",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Home",
        // translateKey: 'nav.pages.welcome',
        icon: "dataDisplay",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.wele34ecome",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Tickets",
        // translateKey: 'nav.pages.welcome',
        icon: "work",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.weldte34ecome",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Documents",
        // translateKey: 'nav.pages.welcome',
        icon: "report",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.weldte34ef4come",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Leave",
        // translateKey: 'nav.pages.welcome',
        icon: "report",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.weldte34ef4cdome",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Timesheets",
        // translateKey: 'nav.pages.welcome',
        icon: "report",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.weldte3rr4ecome",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Chat",
        // translateKey: 'nav.pages.welcome',
        icon: "chat",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.acd43cessDenied",
        path: "/access-denied",
        title: "Reminders",
        // translateKey: 'nav.pages.accessDenied',
        icon: "reminder",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.acces34dttsDenied",
        path: "/access-denied",
        title: "calender",
        // translateKey: 'nav.pages.accessDenied',
        icon: "config",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accesergsDenied",
        path: "/access-denied",
        title: "expense",
        // translateKey: 'nav.pages.accessDenied',
        icon: "expense",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDeeenied",
        path: "/access-denied",
        title: "My assets",
        // translateKey: 'nav.pages.accessDenied',
        icon: "accessDenied",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.acd34recessDeeenied",
        path: "/access-denied",
        title: "Settings",
        // translateKey: 'nav.pages.accessDenied',
        icon: "accessDenied",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
    ],
  },
];

export default pagesNavigationConfig;
