version: '3'

services:
  mongo-5.0:
    image: mongo:5.0
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    volumes:
      - '~/development/docker/volumes/mongodb-5.0/data/db:/data/db'
    ports:
      - "27017:27017"

  redis-5:
    image: redis:5.0
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - '6379:6379'
